### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by agowa338** [rgl/packer-provisioner-windows-update#32]
The build package is unusable.
Can you please provide the exact steps that are required to build this package?

I cloned this repo into a subfolder of `~/Git`.
Than I run the commands from the Readme:
```
go get -u github.com/hashicorp/packer/packer/plugin
go get -u github.com/jteeuwen/go-bindata/...
make
```
It builds and looks like it was successful, but the resulting package cannot be run by packer. "Exit before we could connect"

**Comment by rgl** [comment]
that should have do it. but since this is not yet using go dep... the current/latest versions of the dependencies might not work together, so YMMV.

you could try to follow the last tip from the README "If you are having problems running packer set the PACKER_LOG=1 environment variable to see more information.", maybe that sheds some light into the problem.

**Comment by agowa338** [comment]
I uploaded the resulting file and the log. From the log it is not really obvious, why it fails. Do you see anything?

[packer.log](https://github.com/rgl/packer-provisioner-windows-update/files/2904776/packer.log)
[upload.tar.gz](https://github.com/rgl/packer-provisioner-windows-update/files/2904777/upload.tar.gz)

**Comment by rgl** [comment]
indeed nothing useful ended up in the logs. I will try building this again and add proper go module versioning.

**Comment by rgl** [comment]
can you try with the latest revision? it should now be reproducible.

**Comment by agowa338** [comment]
Now it works, thanks for fixing it.
