### ISSUE TITLE
Known drivers that have no user input is labeled as CanRequestUserInput are skipped

### ISSUE THREAD

**Issue by casz** [rgl/packer-provisioner-windows-update#44]
Using `IsInstalled=0` it is somewhat unexpected that `CanRequestUserInput` is skipped. Especially when I know these two updates actually do not request any User Input as these are drivers and never seen any prompts.
```
   {
      "type": "windows-update",
      "search_criteria": "IsInstalled=0"
    },
```

```
vsphere-clone: Skipped (CanRequestUserInput) Windows update (2019-06-06; 0.05 MB): VMware, Inc. - SCSIAdapter - 4/6/2018 12:00:00 AM - 1.3.10.0
vsphere-clone: Skipped (CanRequestUserInput) Windows update (2019-04-24; 0.08 MB): VMware, Inc. - Net - 10/17/2018 12:00:00 AM - 1.8.10.0
```

**Comment by casz** [comment]
Would be great with an exclusion filter for this code: https://github.com/rgl/packer-provisioner-windows-update/blob/9dbc07901f68d354668422fda4d14f2677a69aa3/update/windows-update.ps1#L194-L197

**Comment by rgl** [comment]
Indeed, its an odd behavior excluding those automatically, but its intention was to be a safeguard, because those flags are supposed to be correctly set, maybe you should warn MS about it (maybe the updates really can also you something in some odd scenario)?.

I'm not really sure we should just remove the test; Maybe we should warn the user instead and tell him how to exclude those updates? Something like:

```powershell
if ($update.InstallationBehavior.CanRequestUserInput) { 
     Write-Output "Warning The following update has the CanRequestUserInput flag set (if the install hangs, you might need to exclude it with the filter exclude:$_.InstallationBehavior.CanRequestUserInput): $updateSummary" 
 } 
```

And move it after the `if (!(Test-IncludeUpdate $updateFilters $update)) {` line.

**Comment by casz** [comment]
Seems reasonable to write a warning
