### ISSUE TITLE
2008R2SP1 stuck in infinite loop on update search

### ISSUE THREAD

**Issue by sbrp** [rgl/packer-provisioner-windows-update#67]
From template:
{
      "type": "windows-update",
      "search_criteria": "IsInstalled=0",
      "filters": [
        "exclude:$_.Title -like '*Preview*'",
        "include:$true"
      ],
      "update_limit": 1000
    }

Log in ADO from Packer pipeline:

    azure-arm: Search for Windows updates failed with 'SucceededWithErrors'. Retrying...

    azure-arm: Waiting for operation to complete (system performance: 27 % cpu; 34 % memory)...

    azure-arm: Search for Windows updates failed with 'SucceededWithErrors'. Retrying...

    azure-arm: Waiting for operation to complete (system performance: 19 % cpu; 33 % memory)...

    azure-arm: Search for Windows updates failed with 'SucceededWithErrors'. Retrying...

    azure-arm: Waiting for operation to complete (system performance: 21 % cpu; 34 % memory)...

This behaviour is repeated until it times out after 6 hours.

The update logic (as opposed to search logic) will force a reboot if this status code is encountered. It would be useful if the same was applied to searching. That or a configurable number of times to search before giving up.

**Comment by rabidpitbull** [comment]
I think this is related to the May Servicing Stack Update (KB4555449).  I had been seeing the same issue in my build scripts - and the windows-update provider was behaving the same way.  I have moved to scripting the installation of the required Servicing Stack Update (KB4490628) and SHA-2 update (KB4474419)  (and rebooting), then installing KB4555449 before trying to run the Windows Update provisioner.

Building Windows 2008 R2 images to support testing is becoming more and more of a puzzle.  I'll be happy when our migrations are complete.

**Comment by rgl** [comment]
I'm sorry, but Windows 2008 is way to old for me to look into.

**Comment by hendrie6** [comment]
I've run into this a few times and finally decided to dig into it.  The latest one I ran into is 2026-01 Security Update (KB5073379) (26100.32230)‌, specifically on Windows 2025.

For those that are unaware, this current module will wait for TiWorker.exe to exit, which is validation that the install has completed.  It then checks to see if a reboot is required and moves on.  What I've found is particular KB's will install fully, but the TiWorker.exe process never exits.  I'm not certain on this, but each one I've run into has been a patch that requires a reboot.  My "assumption" is that the TiWorker.exe not exiting due to that, but it doesn't happen with every one.

I created a fork off of this and will see if I can contribute to the main branch that works around this issue.  I added a new property called 'use_extended_validation'.  Setting use_extended_validation = false follows the same path it does right now where it waits for TiWorker.exe to exit.  Setting use_extended_validation extends the patch validation beyond just TiWorker exiting and pulls in Event logs and CBS logs to determine when patches are done.  It has been working fantastic for me in overcoming this issue.

I also added a 'reboot_delay' that I use during troubleshooting.  If a reboot is required for a patch, it will delay that reboot the number of seconds that you set reboot_delay to.

  provisioner "windows-update" {
    filters         = var.windows_update_filters
    search_criteria = "IsInstalled=0"
    restart_timeout = var.restart_timeout
    **reboot_delay    = 900
    use_extended_validation = false**
  }
